[package]
name = "prompt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xin = { git = "https://github.com/apepkuss/xin.git", branch = "main" }
thiserror = "1"
